image: georgejose/alpine:latest

services:
  - docker:dind

before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - build
  - deploy

build: 
  stage: build
  script:
    - docker-compose build

deploy:
  stage: deploy
  script:
    - ssh ubuntu@georgejose.com 'cd personal_website && git pull --all'
