image: docker:latest

before_script:
  - apk add --no-cache openssh-client
  - eval $(ssh-agent -s)
  - echo $SSH_PRIVATE_KEY > ~/key_variable
  - chmod 400 ~/key_variable
  - ssh-add ~/key_variable && rm -rf ~/key_variable
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - ssh-add -l
    - ssh ubuntu@georgejose.com 'cd personal_website && git pull --all'
