image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache openssh-client rsync py-pip
  - pip install docker-compose
  - eval $(ssh-agent -s)
  - ssh-add < /dev/stdin | $(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - build
  - deploy

build: 
  stage: build
  script:
    - docker-compose build

deploy:
  stage: deploy
  script:
    - ssh ubuntu@georgejose.com 'cd personal_website && git pull --all'
