image: georgejose/docker:latest

services:
  - docker:dind

before_script:
  - sh -c "eval $(ssh-agent -s)""
  - sh -c "ssh-add <(echo "$SSH_PRIVATE_KEY")""
  - sh -c "mkdir -p ~/.ssh"
  - sh -c "'[[ -f /.dockerenv ]] && echo -e \"Host *\n\tStrictHostKeyChecking no\n\n\" > ~/.ssh/config'"

stages:
  - build
  - deploy

build: 
  stage: build
  script:
    - docker-compose build

deploy:
  stage: deploy
  script:
    - ssh ubuntu@georgejose.com 'cd personal_website && git pull --all'