before_install:
  - git clone https://github.com/G2Jose/wheres-my-ttc.git

install:
  - cd wheres-my-ttc
  - yarn
  - cd ..
  - yarn

script:
  - cd wheres-my-ttc
  - CI="" npm run build
  - rm -rf ../public/projects/livetransit/*
  - mv build/* ../public/projects/livetransit/
  - cd ..

after_success:
  - npm install -g firebase-tools
  - firebase deploy
