before_install:
  - git clone https://github.com/G2Jose/wheres-my-ttc.git

install:
  - ls && cd wheres-my-ttc && npm install
  - cd .. && ls
  - npm install

script:
  - ls && cd wheres-my-ttc && CI="" npm run build
  - mv build/* ../public/projects/livetransit/*
