version: '2'
services:
  web:
    build:
      context: web
      dockerfile: 'Dockerfile'
    environment:
      - PERSONAL_WEBSITE_PORT=8080
    ports:
      - '8080:8080'
    volumes:
      - ./web/public:/personal_website/public
  haproxy:
    build:
      context: haproxy
      dockerfile: 'Dockerfile'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./haproxy/ssl:/usr/local/etc/ssl
  # middleware:
  #   environment:
  #     - NODE_ENV=development
  #   build:
  #     context: .
  #     dockerfile: 'config/sails/dockerfile-sails'
  #   environment:
  #     - EXCLUDE_PORTS=443
  #     - VIRTUAL_HOST=*
  #   ports:
  #     - '3003:3003'
  #   volumes:
  #     - ./middleware/api:/middleware/api:ro
