---
platform: linux

image_resource:
  type: docker-image
  source: {repository: docker, tag: dind}

inputs:
- name: resource-personal-website

outputs:
- name: web-docker-image

run:
  path: ./resource-personal-website/.concourse/tasks/build-web-container.sh

params:
  DOCKER_HUB_EMAIL: {{docker-hub-email}}
  DOCKER_HUB_USERNAME: {{docker-hub-username}}
  DOCKER_HUB_PASSWORD: {{docker-hub-password}}
  DOCKER_HUB_IMAGE: georgejose/web