---
platform: linux

image_resource:
  type: docker-image
  source: {repository: docker}

inputs:
- name: personal_website/web

outputs:
- name: web-docker-image

run:
  path: personal_website/.concourse/tasks/build-web-container.sh
