---
platform: linux

image_resource:
  type: docker-image
  source: {repository: docker, tag: dind}

inputs:
- name: resource-personal-website

outputs:
- name: web-docker-image

run:
  path: ./resource-personal-website/.concourse/tasks/build-web-container.sh

params:
  # DOCKER_HUB_EMAIL:
  DOCKER_HUB_USERNAME:
  DOCKER_HUB_PASSWORD:
  DOCKER_HUB_IMAGE: