jobs:
- name: web-job
  public: true
  serial: true
  plan:
  - get: resource-personal_website
  - task: build-web-container
    file: .concourse/tasks/build-web-container.yml
  - task: load-web-container
    file: .concourse/tasks/load-web-container.yml

resources:
- name: resource-personal_website
  type: git
  source:
    uri: https://github.com/G2Jose/personal_website.git
