jobs:
- name: build-web
  public: true
  serial: true
  plan:
  - get: resource-personal-website
    trigger: true
  - task: build-web-container
    file: resource-personal-website/.concourse/tasks/build-web-container.yml
    privileged: true
# - name: load-web
#   public: true
#   serial: true
#   plan:
#   - get: resource-personal-website
#   - task: load-web-container
#     passed: [build-web]
#     trigger: true
#     file: resource-personal-website/.concourse/tasks/load-web-container.yml
#     privileged: true

resources:
- name: resource-personal-website
  type: git
  source:
    uri: https://github.com/G2Jose/personal-website.git
    branch: concourse
